import * as fs from 'fs';
import * as path from 'path';

type SkillSummary = { name: string; description: string };

/**
 * Lê frontmatter YAML simples de um arquivo SKILL.md e retorna name/description.
 * Suporta apenas campos essenciais e não tenta parsear YAML completo.
 */
function parseSkillFrontmatter(filePath: string): SkillSummary | null {
  const content = fs.readFileSync(filePath, 'utf8');
  const lines = content.split(/\r?\n/);
  if (lines.length === 0) return null;
  if (lines[0].trim() !== '---') return null;

  let fm = '';
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === '---') break;
    fm += lines[i] + '\n';
  }

  const nameMatch = fm.match(/^\s*name:\s*(.+)$/m);
  if (!nameMatch) return null;
  const descMatch = fm.match(/^\s*description:\s*(.+)$/m);
  return { name: nameMatch[1].trim(), description: descMatch ? descMatch[1].trim() : '' };
}

/**
 * Varre `.code-skills` (pastas e arquivos .md) e retorna array de SkillSummary.
 */
function listSkills(skillsDir?: string): SkillSummary[] {
  const base = skillsDir || path.join(process.cwd(), '.code-skills');
  if (!fs.existsSync(base)) return [];

  const entries = fs.readdirSync(base, { withFileTypes: true });
  const results: SkillSummary[] = [];

  for (const e of entries) {
    try {
      if (e.isDirectory()) {
        const md = path.join(base, e.name, 'SKILL.md');
        if (fs.existsSync(md)) {
          const s = parseSkillFrontmatter(md);
          if (s) results.push(s);
        }
      } else if (e.isFile() && e.name.endsWith('.md')) {
        const md = path.join(base, e.name);
        const s = parseSkillFrontmatter(md);
        if (s) results.push(s);
      }
    } catch (err) {
      // ignore single-file errors
    }
  }

  return results;
}

/**
 * Gera `src/generated/skillRegistry.ts` com apenas name + description.
 */
function generate(outDir?: string) {
  const skills = listSkills();
  const target = outDir || path.join(process.cwd(), 'src', 'generated');
  if (!fs.existsSync(target)) fs.mkdirSync(target, { recursive: true });

  const outPath = path.join(target, 'skillRegistry.ts');
  const items = skills.map(s => ({ name: s.name, description: s.description }));
  const content = `// Auto-generated by buildSkillRegistry.ts - do not edit manually\n` +
    `export const skillRegistry = ${JSON.stringify(items, null, 2)} as const;\n\nexport default skillRegistry;\n`;

  fs.writeFileSync(outPath, content, 'utf8');
  console.log('[buildSkillRegistry] Wrote', outPath);
}

if (require.main === module) {
  try {
    generate();
  } catch (err) {
    console.error('buildSkillRegistry failed:', err);
    process.exit(1);
  }
}

